# apiVersion: external-secrets.io/v1beta1
# kind: ClusterSecretStore
# metadata:
#   name: vault-backend
# spec:
#   provider:
#     vault:
#       server: "http://vault.security.svc.cluster.local:8200"
#       path: "secret"
#       version: "v2"
#       auth:
#         kubernetes:
#           mountPath: "kubernetes"
#           role: "external-secrets"
#           serviceAccountRef:
#             name: "external-secrets"
#             namespace: "security"
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: grafana-admin
#   namespace: monitoring
# spec:
#   refreshInterval: "1m"
#   secretStoreRef:
#     name: vault-backend
#     kind: ClusterSecretStore
#   target:
#     name: grafana-admin
#     creationPolicy: Owner
#   data:
#   - secretKey: admin-password
#     remoteRef:
#       key: grafana
#       property: password
